add users url & view and model modify
wecode-bootcamp-korea/32-1st-Posea-backend pull request #2
Opened 2022-04-28 13:28 UTC by jeajeongwook

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 아이디, 회원가입 urls / view 작성 

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 이메일로 이용자가 이미 가입된 이용자인지 여부 점검
- check view를 통해 로그인 여부를 확인
- 이미 가입된 이메일이면 로그인 화면으로, 아닐경우 회원가입으로 이동

2. 회원가입 view 작성 및 암호화
- 회원가입시 데이터 정상적으로 들어오는지 확인
- 데이터 확인시 비밀번호 암호화 정상적으로 되는지 여부 확인

3. 로그인 view 작성 및 토큰과 이용자 명 출력여부 확인
- 로그인시 로그인 성공여부 확인, 실패 데이터로 실패여부 확인
- 로그인시 프론트에 토큰 발행하는지 여부 확인
- 로그인시 프론트쪽으로 이용자명 보내주는지 여부 확인
- 
4. 제품 model.py 수정
- 세부내용으로 제품 사용량이 추가되어 product 테이블에 sense 퀄럼 추가 
<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 이미 구현해본 로그인이나 회원가입 view가 아닌 check view를 만들어보면서 생각한데로 코드를 짜고 움직이는 것을 보고 좋았습니다.
- 토큰 발행은 정상적으로 진행했는데 데코레이터를 통해 코드를 좀 더 간소화할 수 있을거 같아 내일은 데코레이터를 중점적으로 알아보고 적용해볼 예정입니다. 

<br />

## :: 기타 질문 및 특이 사항
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시)

2022-05-02 01:32 UTC, jamessoun93 requested changes

2022-05-02 01:32 UTC, jamessoun93 commented on products/models.py
> +    texture    = models.CharField(max_length=100)
`=` 정렬 확인해주세요.

2022-05-02 01:32 UTC, jamessoun93 commented on .gitignore
> +selections.csv
```suggestion
*.csv
```

2022-05-02 01:32 UTC, jamessoun93 commented on cores/validation.py
> +def email_validate(email):
함수명은 가능하다면 동사로 시작할 수 있도록 해주세요.
- `validate_email`
- `validate password`

2022-05-02 01:32 UTC, jamessoun93 commented on posea/urls.py
> +    ]
```suggestion
]
```

2022-05-02 01:32 UTC, jamessoun93 commented on products/models.py
> +    maincategory     = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
```suggestion
    main_category     = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
```

2022-05-02 01:32 UTC, jamessoun93 commented on users/views.py
> +        # 4. email과 password에 대해 유효성 검사 진행
이 순서 다시 한번 고민해보시겠어요?

2022-05-03 05:05 UTC, jamessoun93 requested changes
이제 최종 머지해야하니 주석 다 빼주세요~

2022-05-03 05:30 UTC, jeajeongwook commented
주석 제거 완료했습니다!

2022-05-03 06:06 UTC, merged